/**
 * withBibleWidgets — Expo config plugin for the Android home screen widgets.
 *
 * This project uses Continuous Native Generation: `android/` is gitignored and
 * regenerated by `expo prebuild`, which EAS runs on every cloud build. Any
 * native code written directly into `android/` therefore exists only on the
 * machine that wrote it and silently vanishes from EAS builds.
 *
 * The widgets are pure native (Jetpack Glance), so they have to be re-applied
 * as part of prebuild. This plugin is the source of truth for that: it copies
 * the tracked sources under native/android/ into the generated project and
 * makes the handful of edits the widgets need to the manifest, Gradle files and
 * MainApplication.
 *
 * Everything here is written to be idempotent — prebuild can run repeatedly,
 * and with `--clean` it starts from a fresh template, so each step checks
 * whether its change is already present before applying it.
 */

const {
  withAndroidManifest,
  withAppBuildGradle,
  withProjectBuildGradle,
  withMainApplication,
  withStringsXml,
  withDangerousMod,
  AndroidConfig,
} = require("expo/config-plugins");

const fs = require("fs");
const path = require("path");

/** Java package that owns the widgets. Mirrors the sources in native/android/java. */
const WIDGET_PACKAGE = "pnunag.bibleapp.widgets";

/** Versions pinned together — Glance 1.1.1 requires WorkManager 2.9.x. */
const GLANCE_VERSION = "1.1.1";
const WORK_VERSION = "2.9.1";
const COMPOSE_COMPILER_VERSION = "2.1.20";

/** The three widget receivers, and the XML metadata each one points at. */
const RECEIVERS = [
  { name: "PrayerWidgetReceiver", label: "Prayer Widget", info: "prayer_widget_info" },
  { name: "BibleWidgetReceiver", label: "Bible Widget", info: "bible_widget_info" },
  { name: "MemoryWidgetReceiver", label: "Memory Verse Widget", info: "memory_widget_info" },
];

/** Descriptions shown under each widget in the system picker. */
const WIDGET_STRINGS = {
  prayer_widget_description: "Prayer point and daily prayer goal progress",
  bible_widget_description: "Current Bible passage and chapters read today",
  memory_widget_description: "Top memory verse to review",
};

// ---------------------------------------------------------------------------
// 1. Copy the native sources into the generated project
// ---------------------------------------------------------------------------

/** Recursively copy a directory, creating the destination as needed. */
function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dest);
    else fs.copyFileSync(src, dest);
  }
}

const withWidgetSources = (config) =>
  withDangerousMod(config, [
    "android",
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const platformRoot = cfg.modRequest.platformProjectRoot;

      const source = path.join(projectRoot, "native", "android");
      if (!fs.existsSync(source)) {
        throw new Error(
          `[withBibleWidgets] Expected widget sources at ${source}. ` +
            `Without them the build would silently produce an app with no widgets.`,
        );
      }

      // Kotlin sources land in the package directory the widgets declare.
      copyDir(
        path.join(source, "java"),
        path.join(platformRoot, "app/src/main/java", ...WIDGET_PACKAGE.split(".")),
      );

      // res/ is merged in rather than replaced — the generated project already
      // has drawables and values we must not clobber.
      copyDir(path.join(source, "res"), path.join(platformRoot, "app/src/main/res"));

      return cfg;
    },
  ]);

// ---------------------------------------------------------------------------
// 2. Register the receivers in AndroidManifest.xml
// ---------------------------------------------------------------------------

const withWidgetReceivers = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.receiver = application.receiver ?? [];

    for (const { name, label, info } of RECEIVERS) {
      const androidName = `.widgets.${name}`;
      const exists = application.receiver.some(
        (r) => r.$?.["android:name"] === androidName,
      );
      if (exists) continue;

      application.receiver.push({
        $: {
          "android:name": androidName,
          "android:exported": "true",
          "android:label": label,
        },
        "intent-filter": [
          {
            action: [{ $: { "android:name": "android.appwidget.action.APPWIDGET_UPDATE" } }],
          },
        ],
        "meta-data": [
          {
            $: {
              "android:name": "android.appwidget.provider",
              "android:resource": `@xml/${info}`,
            },
          },
        ],
      });
    }

    return cfg;
  });

// ---------------------------------------------------------------------------
// 3. Widget picker descriptions
// ---------------------------------------------------------------------------

const withWidgetStrings = (config) =>
  withStringsXml(config, (cfg) => {
    for (const [name, value] of Object.entries(WIDGET_STRINGS)) {
      cfg.modResults = AndroidConfig.Strings.setStringItem(
        [{ _: value, $: { name, translatable: "false" } }],
        cfg.modResults,
      );
    }
    return cfg;
  });

// ---------------------------------------------------------------------------
// 4. Gradle — Compose compiler plugin and Glance dependencies
// ---------------------------------------------------------------------------

const withComposeCompilerClasspath = (config) =>
  withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes("compose-compiler-gradle-plugin")) return cfg;

    cfg.modResults.contents = cfg.modResults.contents.replace(
      /classpath\('org\.jetbrains\.kotlin:kotlin-gradle-plugin'\)/,
      `classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')\n    ` +
        `classpath('org.jetbrains.kotlin:compose-compiler-gradle-plugin:${COMPOSE_COMPILER_VERSION}')`,
    );

    return cfg;
  });

const withWidgetGradle = (config) =>
  withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // The widgets are Compose. Without this plugin @Composable lambdas compile
    // as plain Function0 rather than Function2<Composer, Int, Unit>, and Glance
    // fails at runtime with NoSuchMethodError on provideContent.
    if (!contents.includes("org.jetbrains.kotlin.plugin.compose")) {
      contents = contents.replace(
        /apply plugin: "com\.facebook\.react"/,
        `apply plugin: "org.jetbrains.kotlin.plugin.compose"\napply plugin: "com.facebook.react"`,
      );
    }

    // androidx.datastore (pulled in transitively) drags WorkManager back to
    // 2.7.1, which Glance 1.1.1 is not compatible with.
    if (!contents.includes("resolutionStrategy")) {
      contents = contents.replace(
        /^dependencies\s*\{/m,
        `configurations.all {
    resolutionStrategy {
        force "androidx.glance:glance:${GLANCE_VERSION}"
        force "androidx.glance:glance-appwidget:${GLANCE_VERSION}"
        force "androidx.work:work-runtime:${WORK_VERSION}"
        force "androidx.work:work-runtime-ktx:${WORK_VERSION}"
    }
}

dependencies {`,
      );
    }

    // Checked against the implementation line specifically: the
    // resolutionStrategy block above also mentions this artifact, so a looser
    // check would see it and skip adding the dependency itself.
    if (!contents.includes(`implementation("androidx.glance:glance-appwidget`)) {
      contents = contents.replace(
        /^dependencies\s*\{/m,
        `dependencies {
    // Jetpack Glance — home screen widgets.
    implementation("androidx.glance:glance:${GLANCE_VERSION}")
    implementation("androidx.glance:glance-appwidget:${GLANCE_VERSION}")
    implementation("androidx.glance:glance-material3:${GLANCE_VERSION}")
    implementation("androidx.work:work-runtime:${WORK_VERSION}")
    implementation("androidx.work:work-runtime-ktx:${WORK_VERSION}")`,
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

// ---------------------------------------------------------------------------
// 5. Register the native module package
// ---------------------------------------------------------------------------

const withWidgetPackage = (config) =>
  withMainApplication(config, (cfg) => {
    let contents = cfg.modResults.contents;
    const importLine = `import ${WIDGET_PACKAGE}.WidgetBridgePackage`;

    if (!contents.includes(importLine)) {
      // Place it after the last existing import to keep the file valid
      // regardless of what the template imports.
      const imports = [...contents.matchAll(/^import .*$/gm)];
      if (imports.length === 0) {
        throw new Error("[withBibleWidgets] No imports found in MainApplication.");
      }
      const last = imports[imports.length - 1];
      const at = last.index + last[0].length;
      contents = `${contents.slice(0, at)}\n${importLine}${contents.slice(at)}`;
    }

    if (!contents.includes("WidgetBridgePackage()")) {
      // The template builds its package list with `add(MyPackage())` inside
      // PackageList(this).packages.apply { ... }.
      const marker = "add(MyReactNativePackage())";
      if (contents.includes(marker)) {
        contents = contents.replace(marker, `${marker}\n              add(WidgetBridgePackage())`);
      } else {
        // Fall back to the commented hint the template ships with.
        contents = contents.replace(
          /(packages\.apply\s*\{)/,
          `$1\n              add(WidgetBridgePackage())`,
        );
      }
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

// ---------------------------------------------------------------------------

module.exports = function withBibleWidgets(config) {
  config = withWidgetSources(config);
  config = withWidgetReceivers(config);
  config = withWidgetStrings(config);
  config = withComposeCompilerClasspath(config);
  config = withWidgetGradle(config);
  config = withWidgetPackage(config);
  return config;
};
