// Generate the service worker after Expo has written hashed web assets to dist.
// The app shell is cached at install; large book assets are cached when opened.
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const dist = path.join(__dirname, "..", "dist");
const required = ["index.html", "manifest.webmanifest", "icon-192.png", "icon-512.png"];
for (const file of required) {
  if (!fs.existsSync(path.join(dist, file))) {
    throw new Error(`Missing ${file}; run Expo's web export before generating the service worker.`);
  }
}

function listFiles(dir, prefix = "") {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const relative = path.posix.join(prefix, entry.name);
    return entry.isDirectory()
      ? listFiles(path.join(dir, entry.name), relative)
      : [relative];
  });
}

const files = listFiles(dist).filter((file) => file !== "sw.js" && file !== "_headers");
const shellFiles = files.filter((file) => !file.endsWith(".txt"));
const hash = crypto.createHash("sha256");
for (const file of shellFiles.sort()) {
  hash.update(file);
  hash.update(fs.readFileSync(path.join(dist, file)));
}
const version = hash.digest("hex").slice(0, 12);
const urls = ["/", ...shellFiles.map((file) => `/${file}`)];

const source = `// Generated by scripts/generate-pwa-sw.js. Do not edit dist/sw.js.
const SHELL_CACHE = "bible-shell-${version}";
const BOOK_CACHE = "bible-book-assets-v1";
const SHELL_PREFIX = "bible-shell-";
const SHELL_URLS = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    await cache.addAll(SHELL_URLS);
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const oldShells = (await caches.keys())
      .filter((name) => name.startsWith(SHELL_PREFIX) && name !== SHELL_CACHE);
    // Keep the previous build for tabs still running its JavaScript.
    await Promise.all(oldShells.slice(0, -1).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) return response;
      } catch (_) {
        // Use the installed app shell when the network is unavailable.
      }
      return await (await caches.open(SHELL_CACHE)).match("/index.html") || Response.error();
    })());
    return;
  }

  if (!url.pathname.startsWith("/assets/") &&
      !url.pathname.startsWith("/_expo/") &&
      !SHELL_URLS.includes(url.pathname)) return;

  event.respondWith((async () => {
    const isBookAsset = url.pathname.endsWith(".txt");
    const cache = await caches.open(isBookAsset ? BOOK_CACHE : SHELL_CACHE);
    const cached = await cache.match(request) || await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response.ok && response.type !== "opaque") {
      // A full browser cache should not stop a book from loading online.
      event.waitUntil(cache.put(request, response.clone()).catch(() => {}));
    }
    return response;
  })());
});
`;

fs.writeFileSync(path.join(dist, "sw.js"), source);
console.log(`Generated PWA service worker for ${shellFiles.length} app-shell files.`);
