#!/usr/bin/env python3
"""Generate per-chapter study note assets from the canonical combined JSON."""

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "study_notes.json"
OUTPUT = ROOT / "data" / "study-notes"
MANIFEST = ROOT / "src" / "data" / "studyNoteChapterAssets.js"


def main():
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    books_source = (ROOT / "src" / "data" / "books.js").read_text(encoding="utf-8")
    match = re.search(r"export const BOOKS = (\[.*?\]);", books_source, re.DOTALL)
    if not match:
        raise ValueError("Could not read BOOKS from src/data/books.js")
    books = json.loads(match.group(1))

    names = {book["name"] for book in books}
    note_names = {"Song of Songs": "Song Of Solomon"}
    expected = {note_names.get(name, name) for name in names}
    if set(source) != expected:
        raise ValueError(f"Study note books differ: missing={expected - set(source)}, extra={set(source) - expected}")

    OUTPUT.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/split-study-notes.py. Do not edit manually.",
        "// Text assets are read and parsed only when their chapter is opened.",
        "export const STUDY_NOTE_CHAPTER_ASSETS = {",
    ]
    for book in books:
        name = note_names.get(book["name"], book["name"])
        chapters = {str(ch): [] for ch in range(1, book["chapterCount"] + 1)}
        for note in source[name]:
            chapter = str(note["chapter"])
            if chapter not in chapters:
                raise ValueError(f"Invalid chapter {chapter} in {name}")
            chapters[chapter].append(note)
        folder = OUTPUT / book["id"]
        folder.mkdir(parents=True, exist_ok=True)
        lines.append(f"  {json.dumps(book['id'])}: {{")
        for chapter, notes in chapters.items():
            target = folder / f"{chapter}.txt"
            target.write_text(json.dumps(notes, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
            path = f"../../data/study-notes/{book['id']}/{chapter}.txt"
            lines.append(f"    {chapter}: () => require({json.dumps(path)}),")
        lines.append("  },")
    lines.append("};")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")

    for old_file in OUTPUT.glob("*.json"):
        old_file.unlink()

    print(f"Wrote {sum(book['chapterCount'] for book in books)} chapters and {sum(len(notes) for notes in source.values())} notes to {OUTPUT}")


if __name__ == "__main__":
    main()
