#!/usr/bin/env python3
"""Split legacy book assets into chapter assets and generate Metro's static map.

Run after any bible-fetch script that writes a whole-book .txt file. Existing
chapter files are left intact, so the script can be rerun for updated books.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "bible"
MANIFEST = ROOT / "src" / "data" / "bibleChapterAssets.js"
VERSIONS = ("niv", "kjv", "esv", "interlinear")


def main():
    for version in VERSIONS:
        for source in sorted((ASSETS / version).glob("*.txt")):
            book = json.loads(source.read_text(encoding="utf-8"))
            chapters = book["chapters"]
            items = chapters.items() if version == "interlinear" else (
                (chapter["chapter"], chapter) for chapter in chapters
            )
            for number, chapter in items:
                number = int(number)
                target = source.with_suffix("") / f"{number}.txt"
                target.parent.mkdir(parents=True, exist_ok=True)
                payload = {"book": book["book"], "bookId": book["bookId"]}
                if version == "interlinear":
                    payload["chapter"] = number
                    payload["verses"] = chapter
                else:
                    payload["count"] = book["count"]
                    payload["chapter"] = chapter
                target.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
            source.unlink()

    lines = [
        "// Generated by scripts/split-bible-chapters.py. Do not edit manually.",
        "// Static require calls let Metro bundle chapter text as separate assets.",
        "export const BIBLE_CHAPTER_ASSETS = {",
    ]
    for version in VERSIONS:
        lines.append(f"  {version}: {{")
        for book_dir in sorted((ASSETS / version).iterdir()):
            if not book_dir.is_dir():
                continue
            lines.append(f"    {json.dumps(book_dir.name)}: {{")
            for chapter_file in sorted(book_dir.glob("*.txt"), key=lambda p: int(p.stem)):
                number = int(chapter_file.stem)
                path = f"../../assets/bible/{version}/{book_dir.name}/{number}.txt"
                lines.append(f"      {number}: () => require({json.dumps(path)}),")
            lines.append("    },")
        lines.append("  },")
    lines.append("};")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {sum(1 for _ in ASSETS.glob('*/*/*.txt'))} chapter assets and {MANIFEST}")


if __name__ == "__main__":
    main()
