#!/usr/bin/env node
// Stamps src/data/buildInfo.js with the current date + git commit.
// Run automatically via the "prebuild" npm script or manually with:
//   node scripts/stamp-build.js

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "../package.json"), "utf8"));

const date = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

let commit = "unknown";
try {
  commit = execSync("git rev-parse --short HEAD", { stdio: ["pipe", "pipe", "ignore"] })
    .toString()
    .trim();
} catch (_) {}

const out = `// AUTO-GENERATED by scripts/stamp-build.js — do not edit by hand.
// Run \`npm run stamp-build\` or let the EAS prebuild hook do it.
export const BUILD_DATE = "${date}";
export const BUILD_COMMIT = "${commit}";
export const APP_VERSION = "${pkg.version}";
`;

const dest = path.join(__dirname, "../src/data/buildInfo.js");
fs.writeFileSync(dest, out, "utf8");
console.log(`✓ Stamped buildInfo.js  version=${pkg.version}  date=${date}  commit=${commit}`);
